apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: test-cluster
spec:
  postgresVersion: 17
  users:
    - name: svc_pulse_usr
      databases:
        - optdbpulse
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      repos:
      - name: repo1
        s3:
          bucket: ocp-pgbackrest-test
          endpoint: 'https://ceph.omf.cloud'
          region: ev-ceph1
